(deffunction assert-sem-duplicacao-paciente (?paciente)
    (assert-equals 1 (contar-temperatura ?paciente) (str-cat "Sem duplicacao de intensidade-temperatura para " ?paciente))
    (assert-equals 1 (contar-dor-articular ?paciente) (str-cat "Sem duplicacao de intensidade-dor-articular para " ?paciente))
)

(deffunction assert-sem-duplicacao-conclusao (?contador ?mensagem)
    (assert-true (<= ?contador 1) ?mensagem)
)

(deffunction executar-testes-duplicacao ()
    (assert-sem-duplicacao-paciente Temp379)
    (assert-sem-duplicacao-paciente Temp380)
    (assert-sem-duplicacao-paciente Temp390)
    (assert-sem-duplicacao-paciente Temp391)
    (assert-sem-duplicacao-paciente Dor3)
    (assert-sem-duplicacao-paciente Dor4)
    (assert-sem-duplicacao-paciente Dor7)
    (assert-sem-duplicacao-paciente Dor8)
    (assert-sem-duplicacao-paciente NegA)
    (assert-sem-duplicacao-paciente NegB)
    (assert-sem-duplicacao-paciente NegC)

    (assert-sem-duplicacao-conclusao (contar-vinculo NegB dengue) "Sem duplicacao de vinculo-epidemiologico dengue para NegB")
    (assert-sem-duplicacao-conclusao (contar-vinculo NegB chikungunya) "Sem duplicacao de vinculo-epidemiologico chikungunya para NegB")
    (assert-sem-duplicacao-conclusao (contar-vinculo NegB zika) "Sem duplicacao de vinculo-epidemiologico zika para NegB")
    (assert-sem-duplicacao-conclusao (contar-suspeita-clinica NegA dengue) "Sem duplicacao de suspeita-clinica dengue para NegA")
    (assert-sem-duplicacao-conclusao (contar-suspeita-reforcada NegA dengue) "Sem duplicacao de suspeita-reforcada dengue para NegA")
    (assert-sem-duplicacao-conclusao (contar-alerta NegC sinal-alarme-dengue) "Sem duplicacao de alerta sinal-alarme-dengue para NegC")
)
